[package]
name = "blaze-rs"
version = "0.1.2"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
datafusion = "6.0.0"
env_logger = "0.9.0"
jni = "0.19.0"
log = "0.4.14"
prost = "0.9.0"
tokio = "1.15.0"
datafusion-ext = { path = "datafusion-ext" }
plan-serde = { path = "plan-serde" }

[patch.crates-io]
datafusion = { git = "https://github.com/apache/arrow-datafusion.git", rev = "bf715773e66734af87a02845242a1bc48ded8d0f"}
arrow = { git = "https://github.com/apache/arrow-rs.git", rev = "731e132489b99cd688f884642cf20de52aed24d0" }
parquet = { git = "https://github.com/apache/arrow-rs.git", rev = "731e132489b99cd688f884642cf20de52aed24d0" }

[profile.dev]
overflow-checks = false
