[package]
name = "datafusion-ext-commons"
version = "0.1.0"
edition = "2021"
resolver = "1"

[features]
default = ["tokio/rt-multi-thread"]

[dependencies]
arrow = { workspace = true }
arrow-schema = { workspace = true }
async-trait = "0.1.87"
bitvec = "1.0.1"
blaze-jni-bridge = { workspace = true }
bigdecimal = "0.4.7"
byteorder = "1.5.0"
bytes = "1.10.1"
datafusion = { workspace = true }
futures = "0.3"
itertools = "0.14.0"
jni = "0.20.0"
log = "0.4.26"
num = "0.4.2"
once_cell = "1.20.3"
paste = "1.0.15"
radsort = "0.1.1"
tempfile = "3"
thrift = "0.17.0"
tokio = "1.43.0"
unchecked-index = "0.2.2"

[dev-dependencies]
rand = "0.9.0"
