[package]
name = "datafusion-ext-commons"
version = "0.1.0"
edition = "2021"
resolver = "1"

[features]
default = ["tokio/rt-multi-thread"]

[dependencies]
arrow = { workspace = true }
arrow-schema = { workspace = true }
async-trait = "0.1.77"
bitvec = "1.0.1"
blaze-jni-bridge = { workspace = true }
bigdecimal = "0.3.0"
bytes = "1.1.0"
datafusion = { workspace = true }
futures = "0.3"
itertools = "0.10.3"
jni = "0.20.0"
log = "0.4.14"
num = "0.4.0"
once_cell = "1.19.0"
paste = "1.0.7"
postcard = { version = "1.0.8", features = ["alloc"]}
slimmer_box = "0.6.5"
tempfile = "3"
thrift = "0.17.0"
tokio = "1.36"
unchecked-index = "0.2.2"

[dev-dependencies]
rand = "0.8.5"
