[package]
name = "datafusion-ext"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.7.6"
async-trait = "0.1.53"
datafusion = { version = "7.0.0", features = ["simd"] }
futures = "0.3"
jni = "0.19.0"
lazy_static = "1.4.0"
log = "0.4.14"
tokio = { version = "^1.18", features = ["rt-multi-thread"] }
tempfile = "3"
paste = "1.0.7"
once_cell = "1.10.0"
