[package]
name = "datafusion-ext-functions"
version = "0.1.0"
edition = "2021"
resolver = "1"

[dependencies]
arrow = { workspace = true }
async-trait = "0.1.80"
blaze-jni-bridge = { workspace = true }
bigdecimal = "0.4.3"
datafusion = { workspace = true }
datafusion-ext-commons = { workspace = true }
itertools = "0.12.1"
log = "0.4.21"
num = "0.4.2"
paste = "1.0.7"
serde_json = { workspace = true }
sonic-rs = "0.3.5"
