[package]
name = "datafusion-ext-functions"
version = "0.1.0"
edition = "2021"
resolver = "1"

[dependencies]
arrow = { workspace = true }
async-trait = "0.1.77"
blaze-jni-bridge = { workspace = true }
bigdecimal = "0.3.0"
datafusion = { workspace = true }
datafusion-ext-commons = { workspace = true }
itertools = "0.11.0"
log = "0.4.14"
num = "0.4.0"
paste = "1.0.7"
serde_json = { workspace = true }
sonic-rs = "0.3.3"
