[package]
name = "blaze"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
datafusion = { version = "7.0.0", features = ["simd"] }
env_logger = "0.9.0"
jni = "0.19.0"
log = "0.4.14"
prost = "0.9.0"
tokio = { version = "^1.18", features = ["rt-multi-thread"] }
datafusion-ext = { path = "../datafusion-ext" }
plan-serde = { path = "../plan-serde" }
paste = "1.0.7"
snmalloc-rs = { version = "0.2", optional = true }
mimalloc = { version = "0.1", optional = true, default-features = false }
futures = "0.3"
once_cell = "1.10.0"
backtrace = "0.3.65"
panic-message = "0.3.0"

[features]
sn = ["snmalloc-rs"]
mm = ["mimalloc"]
