[package]
name = "blaze"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
backtrace = "0.3.66"
datafusion = { version = "10.0.0", features = ["simd"] }
datafusion-ext = { path = "../datafusion-ext" }
futures = "0.3"
jni = "0.19.0"
log = "0.4.14"
mimalloc = { version = "0.1", optional = true, default-features = false }
once_cell = "1.13.0"
panic-message = "0.3.0"
paste = "1.0.7"
plan-serde = { path = "../plan-serde" }
prost = "0.11.0"
simplelog = "0.12.0"
snmalloc-rs = { version = "0.3", optional = true }
tokio = { version = "^1.20", features = ["rt-multi-thread"] }

[features]
mm = ["mimalloc"]
sn = ["snmalloc-rs"]
