[package]
name = "datafusion-ext-exprs"
version = "0.1.0"
edition = "2021"
resolver = "1"

[dependencies]
arrow = { workspace = true }
async-trait = "0.1.74"
blaze-jni-bridge = { workspace = true }
bigdecimal = "0.3.0"
datafusion = { workspace = true }
datafusion-ext-commons = { workspace = true }
jni = "0.20.0"
log = "0.4.14"
num = "0.4.0"
once_cell = "1.19.0"
parking_lot = "0.12.1"
paste = "1.0.7"
