[package]
name = "datafusion-ext-exprs"
version = "0.1.0"
edition = "2021"
resolver = "1"

[dependencies]
arrow = { workspace = true }
async-trait = "0.1.80"
blaze-jni-bridge = { workspace = true }
bigdecimal = "0.4.3"
datafusion = { workspace = true }
datafusion-ext-commons = { workspace = true }
itertools = "0.13.0"
jni = "0.20.0"
log = "0.4.21"
num = "0.4.2"
once_cell = "1.19.0"
parking_lot = "0.12.3"
paste = "1.0.15"
