name: Build Centos7 Releases

on:
  workflow_dispatch:
  push:
    branches: ["master"]

jobs:
  build-snapshot:
    name: Build Snapshot
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sparkver: [spark-3.0, spark-3.1, spark-3.2, spark-3.3, spark-3.5]
        blazever: [3.0.1]

    steps:
      - uses: actions/checkout@v4
      - uses: s4u/setup-maven-action@main
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - uses: prompt/actions-commit-hash@v3
        id: commit

      - name: Cache blaze-engine-${{ matrix.sparkver }}
        id: cache
        uses: actions/cache@v3
        with:
          path: target-docker/blaze-engine-${{matrix.sparkver}}-release-${{ matrix.blazever }}-SNAPSHOT.jar
          key: blaze-engine-${{matrix.sparkver}}-release-${{ matrix.blazever }}-SNAPSHOT.jar

      - uses: ScribeMD/rootless-docker@0.2.2
        if: steps.cache.outputs.cache-hit != 'true'

      - uses: ScribeMD/docker-cache@0.5.0
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          key: docker-centos7-${{ hashFiles('dev/docker-build/centos7/Dockerfile') }}

      - name: Build blaze-engine-${{ matrix.sparkver }}
        run: |
          sed -i 's/docker-compose -f/docker compose -f/g' ./release-docker.sh
          SHIM=${{ matrix.sparkver }} MODE=release ./release-docker.sh

      - name: Upload blaze-engine-${{ matrix.sparkver }}
        uses: actions/upload-artifact@v3
        with:
          name: blaze-engine-${{matrix.sparkver}}-release-${{ matrix.blazever }}-SNAPSHOT-ce7-${{ steps.commit.outputs.short }}.jar
          path: target-docker/blaze-engine-${{matrix.sparkver}}-release-${{ matrix.blazever }}-SNAPSHOT.jar
