#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Build Centos7 Releases

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - branch-*
  pull_request:
    branches:
      - master
      - branch-*
    paths:
      - '.github/workflows/build-ce7-releases.yml'

jobs:
  build-snapshot:
    name: Build Snapshot
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        sparkver: [spark-3.0, spark-3.1, spark-3.2, spark-3.3, spark-3.4, spark-3.5]
        scalaver: [ 2.12, 2.13 ]
        auronver: [5.0.0]
        runner: [ce7]
        exclude:
          # Only build on scala-2.13 for spark-3.5
          - sparkver: spark-3.0
            scalaver: '2.13'
          - sparkver: spark-3.1
            scalaver: '2.13'
          - sparkver: spark-3.2
            scalaver: '2.13'
          - sparkver: spark-3.3
            scalaver: '2.13'
          - sparkver: spark-3.4
            scalaver: '2.13'

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          submodules: recursive
      - uses:  ./.github/actions/setup-rust-toolchain

      - name: Extract spark version
        run: |
          raw="${{ matrix.sparkver }}"
          ver="${raw#spark-}"
          echo "sparkver_short=$ver" >> $GITHUB_ENV

      - name: Detect osclassfier
        id: detect-osclassfier
        run: |
          osclassfier=$(./build/mvn help:evaluate -Dexpression=os.detected.classifier -q -DforceStdout -P${{ matrix.sparkver }})
          echo "osclassfier=$osclassfier" >> $GITHUB_ENV

      - name: Get short commit hash
        id: commit
        run: echo "short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Cache auron-${{ matrix.sparkver }}_${{ matrix.scalaver }}
        id: cache
        uses: actions/cache@v3
        with:
          path: target-docker/auron-${{matrix.sparkver}}_${{matrix.scalaver}}-release-${{ env.osclassfier }}-${{ matrix.auronver }}-SNAPSHOT.jar
          key: auron-${{matrix.sparkver}}_${{matrix.scalaver}}-release-${{ env.osclassfier }}-${{ matrix.auronver }}-SNAPSHOT.jar

      - name: Build auron-${{ matrix.sparkver }}_${{ matrix.scalaver }}
        run: |
          sed -i 's/docker-compose -f/docker compose -f/g' ./auron-build.sh
          ./auron-build.sh \
          --docker true \
          --release \
          --sparkver ${{ env.sparkver_short }} \
          --scalaver ${{ matrix.scalaver }}

      - name: Upload auron-${{ matrix.sparkver }}_${{ matrix.scalaver }}
        uses: actions/upload-artifact@v4
        with:
          name: auron-${{matrix.sparkver}}_${{matrix.scalaver}}-release-${{ env.osclassfier }}-${{ matrix.auronver }}-SNAPSHOT-${{ matrix.runner }}-${{ steps.commit.outputs.short }}.jar
          path: target-docker/auron-${{matrix.sparkver}}_${{matrix.scalaver}}-release-${{ env.osclassfier }}-${{ matrix.auronver }}-SNAPSHOT.jar
          overwrite: true
